force-app/main/default/objects/Eisenhower_Matrix__c/Eisenhower_Matrix__c.object-meta.xml
<CustomObject>
    <label>Eisenhower Matrix</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Eisenhower Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matrix Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eisenhower_Matrix__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Matrix Type</label>
    <referenceTo>Matrix_Types__c</referenceTo>
    <relationshipLabel>List of Eisenhower Matrix Item Types</relationshipLabel>
    <relationshipName>List_of_Eisenhower_Matrix_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Matrix_Types__c/Matrix_Types__c.object-meta.xml
<CustomObject>
    <label>Matrix Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matrix Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EisenhowerDataService.cls
public with sharing class EisenhowerDataService {
    @AuraEnabled(cacheable=true)
    public static List<Eisenhower_Matrix__c> getMatrixItems(String matrixTypeId) {
      String query =
        'SELECT Name, Is_Done__c, Label__c, Type__c FROM Eisenhower_Matrix__c ';
      if (String.isNotBlank(matrixTypeId)) {
        query += ' WHERE Type__c = :matrixTypeId';
      }
      query += ' WITH SECURITY_ENFORCED ';
      return Database.query(query);
    }

    @AuraEnabled(cacheable=true)
    public static List<Matrix_Types__c> getMatrixTypes() {
        return [
            SELECT Name, Id
            FROM Matrix_Types__c
            WITH SECURITY_ENFORCED
            ORDER BY Name
        ];
    }
}